### ISSUE TITLE
(v2-beta) SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by SQbiz** [LeanMeanFightingMachine/dploy#89]
After installing the beta, running any dploy command gives me this error:

````
/usr/local/lib/node_modules/dploy/index.js:3
import args from './lib/args';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/dploy/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dploy/bin/dploy:3:1)
    at Module._compile (module.js:434:26)
````

Maybe I missed something in the installation? I used:
````
sudo npm install https://github.com/LeanMeanFightingMachine/dploy.git#v2-beta -g
````

**Comment by david-treblig** [comment]
I found the 2.0 beta branch today because I needed the mapping feature, but I have the same error. Have you ever found a solution @SQbiz ? I searched around and found that it might be related to babel compiling es6 so I tried to change babel versions in the package, but to no avail.

**Comment by SQbiz** [comment]
@david-treblig no, never figured this out -- moved on to different solutions

**Comment by david-treblig** [comment]
@SQbiz Dagn... alright, thanks for the quick answer!
